//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceCheckout.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeviceCheckoutEntities : DbContext
    {
        public DeviceCheckoutEntities()
            : base("name=DeviceCheckoutEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deviceInfo> deviceInfo { get; set; }
        public virtual DbSet<devicePreset> devicePreset { get; set; }
        public virtual DbSet<orderInfo> orderInfo { get; set; }
        public virtual DbSet<studentInfo> studentInfo { get; set; }
        public virtual DbSet<zone> zone { get; set; }
    }
}
