//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceCheckout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderInfo
    {
        public int orderId { get; set; }
        public int serialId { get; set; }
        public System.DateTime dateCheckedOut { get; set; }
        public System.DateTime dateCheckIn { get; set; }
    
        public virtual deviceInfo deviceInfo { get; set; }
    }
}
